ALTER TABLE AIRCRAFTDIMENSION SHRINK SPACE;
ALTER TABLE PEOPLEDIMENSION SHRINK SPACE;
ALTER TABLE TEMPORALDIMENSION SHRINK SPACE;
ALTER TABLE MONTHS SHRINK SPACE;
ALTER TABLE AIRCRAFTUTILIZATION SHRINK SPACE;
ALTER TABLE LOGBOOKREPORTING SHRINK SPACE;

-- Run only once
ALTER TABLE AIRCRAFTDIMENSION ADD PRIMARY KEY (ID) USING INDEX PCTFREE 33;
-- Run only once
CREATE BITMAP INDEX IDX_BMP_MODEL_ACRFTUTIL
ON AIRCRAFTUTILIZATION( d.MODEL )
FROM AIRCRAFTUTILIZATION f, AIRCRAFTDIMENSION d
WHERE f.AIRCRAFTID = d.ID;

-- Run only once
CREATE BITMAP INDEX IDX_BMP_AICRAFTID ON AIRCRAFTUTILIZATION(AIRCRAFTID) PCTFREE 0;

-- Run only once
CREATE BITMAP INDEX IDX_BMP_MODEL_LOGBOOKS
ON LOGBOOKREPORTING( d.MODEL )
FROM LOGBOOKREPORTING f, AIRCRAFTDIMENSION d
WHERE f.AIRCRAFTID = d.ID;

-- Run only once
ALTER TABLE PeopleDimension ADD PRIMARY KEY (ID) USING INDEX PCTFREE 33;
-- Run only once
CREATE BITMAP INDEX IDX_BMP_PEOPLE_LOGBOOKS
ON LOGBOOKREPORTING( d.airport )
FROM LOGBOOKREPORTING f, PeopleDimension d
WHERE f.PERSONID = d.ID;

