-- Run only once
--ALTER TABLE AIRCRAFTDIMENSION ADD PRIMARY KEY (ID) USING INDEX PCTFREE 33;
ALTER TABLE AIRCRAFTDIMENSION ADD CONSTRAINT CTR_UNIQUE_AIRCRDIM_ID UNIQUE (ID) USING INDEX PCTFREE 33;
-- Run only once
CREATE BITMAP INDEX IDX_BMP_MODEL_ACRFTUTIL
ON AIRCRAFTUTILIZATION( d.MODEL )
FROM AIRCRAFTUTILIZATION f, AIRCRAFTDIMENSION d
WHERE f.AIRCRAFTID = d.ID PCTFREE 0;

-- Run only once
CREATE BITMAP INDEX IDX_BMP_AICRAFTID ON AIRCRAFTUTILIZATION(AIRCRAFTID) PCTFREE 0;

-- Run only once
CREATE BITMAP INDEX IDX_BMP_MODEL_LOGBOOKS
ON LOGBOOKREPORTING( d.MODEL )
FROM LOGBOOKREPORTING f, AIRCRAFTDIMENSION d
WHERE f.AIRCRAFTID = d.ID PCTFREE 0;

-- Run only once
--ALTER TABLE PeopleDimension ADD PRIMARY KEY (ID) USING INDEX PCTFREE 33;
ALTER TABLE PeopleDimension ADD CONSTRAINT CTR_UNIQUE_PEOPLEDIM_ID UNIQUE (ID) USING INDEX PCTFREE 33;
-- Run only once
CREATE BITMAP INDEX IDX_BMP_PEOPLE_LOGBOOKS
ON LOGBOOKREPORTING( d.airport )
FROM LOGBOOKREPORTING f, PeopleDimension d
WHERE f.PERSONID = d.ID PCTFREE 0;

-- Gather Index Stats
DECLARE esquema VARCHAR2(100);
BEGIN
	SELECT '"'||sys_context('USERENV', 'CURRENT_SCHEMA')||'"' INTO esquema FROM dual;
	DBMS_STATS.GATHER_INDEX_STATS(OWNNAME=>esquema, INDNAME=>'IDX_BMP_MODEL_ACRFTUTIL');
	DBMS_STATS.GATHER_INDEX_STATS(OWNNAME=>esquema, INDNAME=>'IDX_BMP_AICRAFTID');
	DBMS_STATS.GATHER_INDEX_STATS(OWNNAME=>esquema, INDNAME=>'IDX_BMP_MODEL_LOGBOOKS');
	DBMS_STATS.GATHER_INDEX_STATS(OWNNAME=>esquema, INDNAME=>'IDX_BMP_PEOPLE_LOGBOOKS');
END;
-----------------------------------------------------------------------
-----------------------------------------------------------------------
-----------------------------------------------------------------------
--BEFORE OPTIMIZING
--Q1 = 526
--Q2 = 526
--Q3 = 1769
--Q4 = 1808
--Weighted total = 1031
--AFTER OPTIMIZING
--Q1 = 169
--Q2 = 114
--Q3 = 546
--Q4 = 786
--Weighted total = 351,3
--OPTIMIZATION FACTOR = 2,935

